export const URLS = {
  STATIC: [
    'https://palmythology.com',
    'https://palmythology.com/q2n',
    'https://palmythology.com/pantheons',
    'https://palmythology.com/sujets',
    'https://palmythology.com/search',
    'https://palmythology.com/about',
  ],
  PANTHEONS: [
    'https://palmythology.com/pantheons/aztec',
    'https://palmythology.com/pantheons/celtic',
    'https://palmythology.com/pantheons/chinese',
    'https://palmythology.com/pantheons/egyptian',
    'https://palmythology.com/pantheons/greek',
    'https://palmythology.com/pantheons/hindu',
    'https://palmythology.com/pantheons/japanese',
    'https://palmythology.com/pantheons/mayan',
    'https://palmythology.com/pantheons/norse',
    'https://palmythology.com/pantheons/roman',
  ],
  SUBJECTS: [
    'https://palmythology.com/subjects/divinity',
    'https://palmythology.com/subjects/person',
    'https://palmythology.com/subjects/monster',
    'https://palmythology.com/subjects/tribe',
    'https://palmythology.com/subjects/writings',
    'https://palmythology.com/subjects/place',
  ],
  CARDS: [
    'https://palmythology.com/cards/aztec/quetzacoatl',
    'https://palmythology.com/cards/aztec/tepotzecatl',
    'https://palmythology.com/cards/aztec/xochipili',

    'https://palmythology.com/cards/celtic/artio',
    'https://palmythology.com/cards/celtic/belisama',
    'https://palmythology.com/cards/celtic/brigit',
    'https://palmythology.com/cards/celtic/camulos',
    'https://palmythology.com/cards/celtic/cernunnos',
    'https://palmythology.com/cards/celtic/cuchulainn',
    'https://palmythology.com/cards/celtic/dana',
    'https://palmythology.com/cards/celtic/epona',
    'https://palmythology.com/cards/celtic/esus',
    'https://palmythology.com/cards/celtic/fomoires',
    'https://palmythology.com/cards/celtic/gundestrup',
    'https://palmythology.com/cards/celtic/morrigan',
    'https://palmythology.com/cards/celtic/oengus',

    'https://palmythology.com/cards/chinese/fuxi',
    'https://palmythology.com/cards/chinese/nuwa',
    'https://palmythology.com/cards/chinese/shennong',
    'https://palmythology.com/cards/chinese/sun-wukong',

    'https://palmythology.com/cards/egyptian/anubis',
    'https://palmythology.com/cards/egyptian/apis',
    'https://palmythology.com/cards/egyptian/bastet',
    'https://palmythology.com/cards/egyptian/enneade',
    'https://palmythology.com/cards/egyptian/horus',
    'https://palmythology.com/cards/egyptian/isis',
    'https://palmythology.com/cards/egyptian/livre-des-morts',
    'https://palmythology.com/cards/egyptian/neith',
    'https://palmythology.com/cards/egyptian/nephtys',
    'https://palmythology.com/cards/egyptian/ogdoade',
    'https://palmythology.com/cards/egyptian/osiris',
    'https://palmythology.com/cards/egyptian/ptah',
    'https://palmythology.com/cards/egyptian/re',
    'https://palmythology.com/cards/egyptian/sekhmet',
    'https://palmythology.com/cards/egyptian/seth',
    'https://palmythology.com/cards/egyptian/sobek',
    'https://palmythology.com/cards/egyptian/sphinx',
    'https://palmythology.com/cards/egyptian/tefnout',
    'https://palmythology.com/cards/egyptian/thot',

    'https://palmythology.com/cards/greek/aphrodite',
    'https://palmythology.com/cards/greek/arachne',
    'https://palmythology.com/cards/greek/ares',
    'https://palmythology.com/cards/greek/artemis',
    'https://palmythology.com/cards/greek/athena',
    'https://palmythology.com/cards/greek/bellerophon',
    'https://palmythology.com/cards/greek/circe',
    'https://palmythology.com/cards/greek/demeter',
    'https://palmythology.com/cards/greek/dionysos',
    'https://palmythology.com/cards/greek/hades',
    'https://palmythology.com/cards/greek/ixion',
    'https://palmythology.com/cards/greek/persee',
    'https://palmythology.com/cards/greek/perseĥone',
    'https://palmythology.com/cards/greek/poseidon',
    'https://palmythology.com/cards/greek/sisyphe',
    'https://palmythology.com/cards/greek/ulysse',
    'https://palmythology.com/cards/greek/zeus',

    'https://palmythology.com/cards/hindu/agni',
    'https://palmythology.com/cards/hindu/ganesh',
    'https://palmythology.com/cards/hindu/indra',
    'https://palmythology.com/cards/hindu/shiva',

    'https://palmythology.com/cards/japanese/akkorokamui',
    'https://palmythology.com/cards/japanese/fujin',
    'https://palmythology.com/cards/japanese/inari',
    'https://palmythology.com/cards/japanese/kappa',
    'https://palmythology.com/cards/japanese/le-monde-des-yokai',
    'https://palmythology.com/cards/japanese/myobu',
    'https://palmythology.com/cards/japanese/raijin',
    'https://palmythology.com/cards/japanese/tanuki',
    'https://palmythology.com/cards/japanese/tsuchigumo',
    'https://palmythology.com/cards/japanese/yamata-no-orochi',

    'https://palmythology.com/cards/mayan/camazotz',
    'https://palmythology.com/cards/mayan/hunab-ku',
    'https://palmythology.com/cards/mayan/kukulkan',
    'https://palmythology.com/cards/mayan/popol-vuh',
    'https://palmythology.com/cards/mayan/xquic',

    'https://palmythology.com/cards/norse/asgard',
    'https://palmythology.com/cards/norse/baldr',
    'https://palmythology.com/cards/norse/einherjar',
    'https://palmythology.com/cards/norse/forseti',
    'https://palmythology.com/cards/norse/freyja',
    'https://palmythology.com/cards/norse/freyr',
    'https://palmythology.com/cards/norse/frigg',
    'https://palmythology.com/cards/norse/futhark',
    'https://palmythology.com/cards/norse/heimdall',
    'https://palmythology.com/cards/norse/idunn',
    'https://palmythology.com/cards/norse/jotnar',
    'https://palmythology.com/cards/norse/loki',
    'https://palmythology.com/cards/norse/nidavellir',
    'https://palmythology.com/cards/norse/njord',
    'https://palmythology.com/cards/norse/nornes',
    'https://palmythology.com/cards/norse/odin',
    'https://palmythology.com/cards/norse/thor',
    'https://palmythology.com/cards/norse/tyr',

    'https://palmythology.com/cards/roman/flora',
    'https://palmythology.com/cards/roman/janus',
    'https://palmythology.com/cards/roman/jupiter',
  ],
}
