const colors = require("tailwindcss/colors");

module.exports = {
  purge: {
    content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
    safelist: [
      "bg-amber-500",
      "bg-amber-600",
      "bg-blue-700",
      "bg-emerald-700",
      "bg-neutral-100",
      "bg-orange-600",
      "bg-purple-800",
      "bg-red-700",
      "bg-red-900",
      "bg-sky-300",
      "from-amber-500",
      "from-blue-500",
      "from-cyan-500",
      "from-green-500",
      "from-purple-500",
      "from-red-500",
      "lg:hover:bg-amber-500",
      "lg:hover:bg-amber-600",
      "lg:hover:bg-blue-700",
      "lg:hover:bg-emerald-700",
      "lg:hover:bg-neutral-100",
      "lg:hover:bg-orange-600",
      "lg:hover:bg-purple-800",
      "lg:hover:bg-red-700",
      "lg:hover:bg-red-900",
      "lg:hover:bg-sky-300",
      "lg:hover:text-emerald-600",
      "lg:hover:text-gray-100",
      "lg:hover:text-red-700",
      "lg:hover:text-yellow-500",
      "text-emerald-600",
      "text-gray-100",
      "text-red-700",
      "text-yellow-500",
      "to-green-500",
      "to-indigo-500",
      "to-lime-500",
      "to-pink-500",
      "to-yellow-500",
    ],
  },
  darkMode: "media",
  theme: {
    extend: {
      colors: {
        inherit: colors.inherit,
        current: colors.current,
        transparent: colors.transparent,
        black: colors.black,
        white: colors.white,
        slate: colors.slate,
        gray: colors.gray,
        zinc: colors.zinc,
        neutral: colors.neutral,
        stone: colors.stone,
        red: colors.red,
        orange: colors.orange,
        amber: colors.amber,
        yellow: colors.yellow,
        lime: colors.lime,
        green: colors.green,
        emerald: colors.emerald,
        teal: colors.teal,
        cyan: colors.cyan,
        sky: colors.sky,
        blue: colors.blue,
        indigo: colors.indigo,
        violet: colors.violet,
        purple: colors.purple,
        fuchsia: colors.fuchsia,
        pink: colors.pink,
        rose: colors.rose,
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
