const STANDARD_SIZES = {
	EXTRA_SMALL: "xs",
	SMALL: "sm",
	NORMAL: "base",
	LARGE: "lg",
	EXTRA_LARGE: "xl",
};

export const SIZES = {
	EXTRA_SMALL: STANDARD_SIZES.EXTRA_SMALL,
	SMALL: STANDARD_SIZES.SMALL,
	NORMAL: STANDARD_SIZES.NORMAL,
	LARGE: STANDARD_SIZES.LARGE,
	EXTRA_LARGE: STANDARD_SIZES.EXTRA_LARGE,
	TWO_XL: `2${STANDARD_SIZES.EXTRA_LARGE}`,
	THREE_XL: `3${STANDARD_SIZES.EXTRA_LARGE}`,
	FOUR_XL: `4${STANDARD_SIZES.EXTRA_LARGE}`,
	FIVE_XL: `5${STANDARD_SIZES.EXTRA_LARGE}`,
	SIX_XL: `6${STANDARD_SIZES.EXTRA_LARGE}`,
	SEVEN_XL: `7${STANDARD_SIZES.EXTRA_LARGE}`,
	EIGHT_XL: `8${STANDARD_SIZES.EXTRA_LARGE}`,
	NINE_XL: `9${STANDARD_SIZES.EXTRA_LARGE}`,
};
