export const URLS = {
	STATIC: [
		"https://palmythology.com",
		"https://palmythology.com/q2n",
		"https://palmythology.com/pantheons",
		"https://palmythology.com/sujets",
		"https://palmythology.com/search",
		"https://palmythology.com/about",
	],
	PANTHEONS: [
		"https://palmythology.com/pantheons/aztec",
		"https://palmythology.com/pantheons/celtic",
		"https://palmythology.com/pantheons/chinese",
		"https://palmythology.com/pantheons/egyptian",
		"https://palmythology.com/pantheons/greek",
		"https://palmythology.com/pantheons/hindu",
		"https://palmythology.com/pantheons/japanese",
		"https://palmythology.com/pantheons/mayan",
		"https://palmythology.com/pantheons/mesopotamian",
		"https://palmythology.com/pantheons/norse",
		"https://palmythology.com/pantheons/roman",
	],
	SUBJECTS: [
		"https://palmythology.com/subjects/event",
		"https://palmythology.com/subjects/divinity",
		"https://palmythology.com/subjects/person",
		"https://palmythology.com/subjects/monster",
		"https://palmythology.com/subjects/tribe",
		"https://palmythology.com/subjects/writings",
		"https://palmythology.com/subjects/place",
	],
};
